<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5SqjfvX\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5SqjfvX/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container5SqjfvX.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container5SqjfvX\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container5SqjfvX\App_KernelProdContainer([
    'container.build_hash' => '5SqjfvX',
    'container.build_id' => 'ab95c47f',
    'container.build_time' => 1637538495,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5SqjfvX');
