<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOib6MXW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOib6MXW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOib6MXW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOib6MXW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOib6MXW\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oib6MXW',
    'container.build_id' => 'd130faa4',
    'container.build_time' => 1637797114,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOib6MXW');
