<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXD34YUf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXD34YUf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXD34YUf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXD34YUf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXD34YUf\App_KernelDevDebugContainer([
    'container.build_hash' => 'XD34YUf',
    'container.build_id' => 'd64be15b',
    'container.build_time' => 1640103031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXD34YUf');
