<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_app_about_getabout' => [[], ['_controller' => 'App\\Controller\\AboutController::getAboutAction'], [], [['text', '/api/about']], [], []],
    'api_app_about_postbook' => [[], ['_controller' => 'App\\Controller\\AboutController::postBookAction'], [], [['text', '/api/about']], [], []],
    'api_app_about_borrow' => [['id'], ['_controller' => 'App\\Controller\\AboutController::borrow'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book/borrow']], [], []],
    'api_app_about_return' => [['id'], ['_controller' => 'App\\Controller\\AboutController::return'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book/return']], [], []],
    'api_app_about_getoverduebooks' => [[], ['_controller' => 'App\\Controller\\AboutController::getOverdueBooksAction'], [], [['text', '/api/overdue']], [], []],
    'api_app_book_getbook' => [[], ['_controller' => 'App\\Controller\\BookController::getBookAction'], [], [['text', '/api/books']], [], []],
    'api_app_book_postbook' => [[], ['_controller' => 'App\\Controller\\BookController::postBookAction'], [], [['text', '/api/book']], [], []],
    'api_app_book_borrow' => [['id'], ['_controller' => 'App\\Controller\\BookController::borrow'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book/borrow']], [], []],
    'api_app_book_return' => [['id'], ['_controller' => 'App\\Controller\\BookController::return'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book/return']], [], []],
    'api_app_book_getoverduebooks' => [[], ['_controller' => 'App\\Controller\\BookController::getOverdueBooksAction'], [], [['text', '/api/overdue']], [], []],
    'api_app_offer_getoffer' => [[], ['_controller' => 'App\\Controller\\OfferController::getOfferAction'], [], [['text', '/api/offer']], [], []],
    'api_app_offer_postbook' => [[], ['_controller' => 'App\\Controller\\OfferController::postBookAction'], [], [['text', '/api/offer']], [], []],
    'api_app_rodo_getrodo' => [[], ['_controller' => 'App\\Controller\\RodoController::getRodoAction'], [], [['text', '/api/rodo']], [], []],
    'api_app_rodo_postbook' => [[], ['_controller' => 'App\\Controller\\RodoController::postBookAction'], [], [['text', '/api/rodo']], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '.+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '.+', 'shortName', true], ['text', '/api/contexts']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'authentication_token' => [[], [], [], [['text', '/authentication_token']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
];
